name: Docker-Publish

on:
  schedule:
    # Recompile at 00:15 UTC on Sundays
    - cron: '15 0 * * 0'
    
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  workflow_dispatch:
    # Allow this event to be triggered in the github ui

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: petsc-build

jobs:
  get-version:
    runs-on: ubuntu-latest 
    steps:
    - id: version
      run: |
        # Get the latest version of petsc 
        export PETSC_COMMIT=$(git ls-remote https://gitlab.com/petsc/petsc.git HEAD | awk '{ print substr($1, 1, 8)}'D)
        echo "::set-output name=petsc_commit::${PETSC_COMMIT}"
        
    outputs:
      petsc_commit: ${{ steps.version.outputs.petsc_commit }}
      
  
  # Push image to GitHub Packages.
  build:
    needs: get-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64,linux/amd64]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    
          
      - name: checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-


      - name: Build image
        run: |
          # define the image id
          PLATFORM_NAME=$(echo ${{ matrix.platform }} | tr -d / ')
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME-$PLATFORM_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{ needs.get-version.outputs.petsc_commit}}
          echo PLATFORM=${{ matrix.platform }}
          
          # Build the image
          docker buildx build .\
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform ${{ matrix.platform }}
            --build-arg PETSC_BUILD_COMMIT=${{ needs.get-version.outputs.petsc_commit}}
            --load
            --tag $IMAGE_ID:${{ needs.get-version.outputs.petsc_commit}}
            --file Dockerfile    
     

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    strategy:
      matrix:
        platform: [linux/arm64,linux/amd64]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1            
          
      - uses: actions/checkout@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-


      - name: Build image
        run: |
          # define the image id
          PLATFORM_NAME=$(echo ${{ matrix.platform }} | tr -d / ')
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME-$PLATFORM_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{ needs.get-version.outputs.petsc_commit}}
          echo PLATFORM=${{ matrix.platform }}
          
          # Build the image
          docker buildx build .\
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform ${{ matrix.platform }}
            --build-arg PETSC_BASE_IMAGE=$IMAGE_ID:${{ needs.get-version.outputs.petsc_commit}}
            --file DockerAblateFile    
          
